### ISSUE TITLE
[Feature Request] Combat cooldowns for teleport-related commands.

### ISSUE THREAD

**Issue by LadyHaley** [nulli0n/SunLight-spigot#10]
Combat cooldowns for teleport-related commands.
This is one aspect that Essentials does better, it's an essential feature for pvp based survival servers, and without the feature, sunlight just isn't a viable choice

**Comment by nulli0n** [comment]
This is not just command cooldown, but the teleport delay itself. And while we can add such delays inside SL commands, this delay will not work when using homes, warps, etc from GUIs or other places. Adding such delay in that places will result in a huge mess, because it also will prevent instant teleport when it's really needed. This will require workarounds or something else I don't want to do.

Second, even if we do this inside all SL modules and commands, you can still have other teleport-related plugins that will be ignored and can be used to bypass it. As many people says, it's a combat feature, and it's a job of the combat-related plugins to have such feature then. I don't see a reason why it should be added to SunLight. We are not going to replicate all the Essentials features just due to fact it has them.

So, unfortunately, won't add.

**Comment by LadyHaley** [comment]
That makes sense. Thank you for your time and response!!!
